name: Run script hourly

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      BLSKY_HANDLE: ${{ secrets.BLSKY_HANDLE }}
      BLSKY_APP_PASSWORD: ${{ secrets.BLSKY_APP_PASSWORD }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U python-dotenv atproto tweepy

      - name: Run script
        run: python hoelaatishet.py
