name: Run script hourly

on:
  schedule:
    - cron: "0 * * * *" # Elke uur op het uur
  workflow_dispatch: # Handmatig starten mogelijk

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      BLSKY_HANDLE: ${{ secrets.BLSKY_HANDLE }}
      BLSKY_APP_PASSWORD: ${{ secrets.BLSKY_APP_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install python-dotenv atproto datetime
      - name: Run script
        run: python hoelaatishet.py
