name: FDV script daily at 7 UTC

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      BLSKY_FDV_HANDLE: ${{ secrets.BLSKY_FDV_HANDLE }}
      BLSKY_FDV_APP_PASSWORD: ${{ secrets.BLSKY_FDV_APP_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U python-dotenv atproto

      - name: Run script
        run: python fijnedagvan.py
